### ISSUE TITLE
DockerHub Readme get not updated on Image Push

### ISSUE THREAD

**Issue by Rindula** [yadomi/docker-repetier-server#17]
Tried to fix in adb10099bf664014d258f6828bebb16bf59bdeee and 39634cf13da637deef70357a583eac87b847657c but there seem to be not enough permissions on the token ... Or it requires the password

**Comment by yadomi** [comment]
Indeed good catch, might be an issue related to this https://github.com/peter-evans/dockerhub-description/issues/10#issuecomment-586795630. I will take a look at it soon. (I’ve updated the readme on dockerhub manually in the mean time)

**Comment by Rindula** [comment]
> Indeed good catch, might be an issue related to this [peter-evans/dockerhub-description#10 (comment)](https://github.com/peter-evans/dockerhub-description/issues/10#issuecomment-586795630). I will take a look at it soon. (I’ve updated the readme on dockerhub manually in the mean time)

@yadomi Any progress on it yet?

**Comment by yadomi** [comment]
@Rindula sadly, I didn't find any viable solution yet that works with either a dockerhub token or a dockerhub account with 2FA enabled. That's not possible with current dockerhub api and github action without compromising the security of the dockerhub account.

What I did in the meantime is that I've updated the [README on dockerhub](https://hub.docker.com/r/yadomi/repetier-server) with build and version badges from shields.io, removed the instruction/usage and added a link to this repo

> For usage instruction, see the README.md on the Github repository: https://github.com/yadomi/docker-repetier-server

That way the badge will reflect the most up-to-date tag on this repository, we just have to make sure to push the tag as well when updating the image
