### ISSUE TITLE
FFMPEG support

### ISSUE THREAD

**Issue by wiuwiu** [yadomi/docker-repetier-server#25]
Hi.
Is it possible to add ffmpeg packages into Dockerfile to have Timelapse in Repetier-Server?

**Comment by yadomi** [comment]
Hi @wiuwiu,

That's a good idea, I'll tweak around to see if everything is ok with ffmpeg and add it if it work 👍

**Comment by wiuwiu** [comment]
I just put:
`# Add ffmpeg support.
RUN apt update 2>/dev/null \
    && apt install ffmpeg -y 2>/dev/null`

into Dockerfile.

**Comment by yadomi** [comment]
Done via https://github.com/yadomi/docker-repetier-server/pull/30, in v1.4.10
