### ISSUE TITLE
New Version 1.4.13

### ISSUE THREAD

**Issue by DarthDestroyer** [yadomi/docker-repetier-server#31]
VERSION="1.4.13"

Just a small Version Reminder ;)

**Comment by LuckyTurtleDev** [comment]
I have a fork with the current version now: [LuckyTurtleDev/docker-images](https://github.com/LuckyTurtleDev/docker-images/tree/main/dockerfiles/repetier-server)

**Comment by yadomi** [comment]
Apologies for the delay, I've updated to [v1.4.14](https://github.com/yadomi/docker-repetier-server/releases/tag/v1.4.14)
