### ISSUE TITLE
Display output from docker container?

### ISSUE THREAD

**Issue by sbazzell** [yadomi/docker-repetier-server#8]
Is it possible to run repetier-server in a docker container, but still have it output/interact with a touchscreen?

**Comment by yadomi** [comment]
Hello, I'm not sure if I understand correctly, are you talking about the web UI of repetier accessible from the browser when the server is running ? (eg: `localhost:3344` ) or a touchscreen on your printer ?

**Comment by sbazzell** [comment]
> Hello, I'm not sure if I understand correctly, are you talking about the web UI of repetier accessible from the browser when the server is running ? (eg: `localhost:3344` ) or a touchscreen on your printer ?

Yes, I'm referring to a touchscreen connected to the Pi.

**Comment by yadomi** [comment]
You'll have better results by asking directly on the official [repetier forum](https://forum.repetier.com/) or asking support related to your printer

**Comment by sbazzell** [comment]
> 
> 
> You'll have better results by asking directly on the official [repetier forum](https://forum.repetier.com/) or asking support related to your printer

Repetier Server is setup on a dedicated Pi3 outside the printer.   The printer is irrelevant.  My question is purely docker-related concerning **this** image.  Can this image communicate with a touchscreen?

Getting to the web UI of a docker container is easy.  What I want to know is if you've been able to get this image to be able to communicate with a touchscreen connected to the docker host.

**Comment by yadomi** [comment]
My printers does not have any touchscreen, but if you're a referring to [this interface](https://www.repetier-server.com/booting-into-touchscreen-mode-for-linux/) from repetier, this docker image should be able to provide it once you've configured your printer and setuped the license.

In fact, you can access the interface via `http://<host-ip>:3344/modules/front2/www/app.html` (where `3344` is the port when runned with `-p 3344:3344` and `host-ip` the ip of the machine on where you run the container)

So I guess it should work as expected if you have this image running on the same pi you have your touchscreen, you could use either `localhost:3344` or your pi `ip:3344`

If you want to access repetier with different ip and don't bother with port forwarding you can create [docker vlan](https://docs.docker.com/engine/reference/commandline/network_create/)

**Comment by sbazzell** [comment]
> 
> 
> My printers does not have any touchscreen, but if you're a referring to [this interface](https://www.repetier-server.com/booting-into-touchscreen-mode-for-linux/) from repetier, this docker image should be able to provide it once you've configured your printer and setuped the license.
> 
> In fact, you can access the interface via `http://<host-ip>:3344/modules/front2/www/app.html` (where `3344` is the port when runned with `-p 3344:3344` and `host-ip` the ip of the machine on where you run the container)
> 
> So I guess it should work as expected if you have this image running on the same pi you have your touchscreen, you could use either `localhost:3344` or your pi `ip:3344`
> 
> If you want to access repetier with different ip and don't bother with port forwarding you can create [docker vlan](https://docs.docker.com/engine/reference/commandline/network_create/)

I guess what I was looking for is really quite niche and out of the standard realm for docker.  My hope was to run docker under a GUI-less host (like ubuntu server).  The container would directly interface with the touchscreen via LVDS or I2C or something.  The container would obviously need to be run in privileged mode and be mapped to the touchscreen device (to be honest I can't remember if the touchscreen is I2C or LVDS).  Torizon Storyboard does exactly this for embedded systems.

That being said, running a GUI docker host and just having the PI automatically execute a browser session in full screen pointed at that URL would effectively accomplish the same goal.

**Comment by yadomi** [comment]
> I guess what I was looking for is really quite niche and out of the standard realm for docker. 

I think this _could_ work with docker itself if repetier-server has the support for it but it is a bit beyond of _this_ docker image. This image just put repetier-server in a container nothing else. 

I'm closing the issue but if you think I'm missing something, feel free to open a new one.
